# Aprimoramentos Positivos
Improvement.create(name: "Acerto Crítico Aprimorado I")
Improvement.create(name: "Acerto Crítico Aprimorado II")
Improvement.create(name: "Acerto Crítico Aprimorado III")
Improvement.create(name: "Acuidade com arma")
Improvement.create(name: "Alcance Mágico Extendido")
Improvement.create(name: "Alma Dupla I")
Improvement.create(name: "Alma Dupla II")
Improvement.create(name: "Alma Gêmea")
Improvement.create(name: "Alma Pura")
Improvement.create(name: "Alvo Elusivo I")
Improvement.create(name: "Alvo Elusivo II")
Improvement.create(name: "Ambidestria")
Improvement.create(name: "Ambiente Favorável I")
Improvement.create(name: "Ambiente Favorável II")
Improvement.create(name: "Ambiente Favorável III")
Improvement.create(name: "Ambiente Favorável IV")
Improvement.create(name: "Amor Verdadeiro")
Improvement.create(name: "Aparência Inofensiva")
Improvement.create(name: "Arma ou Amuleto Mágico I")
Improvement.create(name: "Arma ou Amuleto Mágico II")
Improvement.create(name: "Arma Preferencial")
Improvement.create(name: "Armadura de Heróis I")
Improvement.create(name: "Armadura de Heróis II")
Improvement.create(name: "Armadura de Heróis III")
Improvement.create(name: "Ataque Brutal")
Improvement.create(name: "Ataque Desarmado I")
Improvement.create(name: "Ataque Desarmado II")
Improvement.create(name: "Ataque Desarmado III")
Improvement.create(name: "Ataque Desarmado IV")
Improvement.create(name: "Ataque Furtivo I")
Improvement.create(name: "Ataque Furtivo II")
Improvement.create(name: "Ataque Furtivo III")
Improvement.create(name: "Ataque Poderoso")
Improvement.create(name: "Atravessar I")
Improvement.create(name: "Atravessar II")
Improvement.create(name: "Biblioteca I")
Improvement.create(name: "Biblioteca II")
Improvement.create(name: "Biblioteca III")
Improvement.create(name: "Biblioteca IV")
Improvement.create(name: "Biblioteca Mística I")
Improvement.create(name: "Biblioteca Mística II")
Improvement.create(name: "Biblioteca Mística III")
Improvement.create(name: "Bom Senso")
Improvement.create(name: "Caçador de Demônios ou Anjos I")
Improvement.create(name: "Caçador de Demônios ou Anjos II")
Improvement.create(name: "Caminho da Floresta")
Improvement.create(name: "Canalizador I ")
Improvement.create(name: "Canalizador II")
Improvement.create(name: "Capaz de Enxergar Auras")
Improvement.create(name: "Capaz de Enxergar Espíritos")
Improvement.create(name: "Classe Social I")
Improvement.create(name: "Classe Social II")
Improvement.create(name: "Classe Social III")
Improvement.create(name: "Clero I")
Improvement.create(name: "Clero II")
Improvement.create(name: "Clero III")
Improvement.create(name: "Companheiro Animal")
Improvement.create(name: "Comunicação em Sonhos")
Improvement.create(name: "Concentração")
Improvement.create(name: "Conhecimentos Arcanos")
Improvement.create(name: "Conjuração")
Improvement.create(name: "Contatos e Aliados I")
Improvement.create(name: "Contatos e Aliados II")
Improvement.create(name: "Contatos e Aliados III")
Improvement.create(name: "Contatos e Aliados IV")
Improvement.create(name: "Controle de Multidões")
Improvement.create(name: "Coração de Guerreiro")
Improvement.create(name: "Coragem")
Improvement.create(name: "Corpo Fechado")
Improvement.create(name: "Corpo Maleável")
Improvement.create(name: "Detectar Magia I")
Improvement.create(name: "Detectar Magia II")
Improvement.create(name: "Divida de Gratidão I")
Improvement.create(name: "Divida de Gratidão II")
Improvement.create(name: "Divida de Gratidão III")
Improvement.create(name: "Duro de Matar")
Improvement.create(name: "Efeitos Mágicos Permanentes")
Improvement.create(name: "Eloqüente")
Improvement.create(name: "Empatia com Animais")
Improvement.create(name: "Especialista em Caminho")
Improvement.create(name: "Especialização em Arma I")
Improvement.create(name: "Especialização em Arma II")
Improvement.create(name: "Esquiva Sobrenatural")
Improvement.create(name: "Estender Magia")
Improvement.create(name: "Evasão")
Improvement.create(name: "Fama I")
Improvement.create(name: "Fama II")
Improvement.create(name: "Fama III")
Improvement.create(name: "Fama IV")
Improvement.create(name: "Família ou Mentor Honrado")
Improvement.create(name: "Familiares")
Improvement.create(name: "Gremilins")
Improvement.create(name: "Guardião I")
Improvement.create(name: "Guardião II")
Improvement.create(name: "Guardião de Artefato")
Improvement.create(name: "Homúnculo")
Improvement.create(name: "Identidade Secreta")
Improvement.create(name: "Improvisador I")
Improvement.create(name: "Improvisador II")
Improvement.create(name: "Imunidade a Venenos I")
Improvement.create(name: "Imunidade a Venenos II")
Improvement.create(name: "Infravisão")
Improvement.create(name: "Inimigo Favorito")
Improvement.create(name: "Inocência I")
Improvement.create(name: "Inocência II")
Improvement.create(name: "Itens Mágicos I")
Improvement.create(name: "Itens Mágicos II")
Improvement.create(name: "Itens Mágicos III")
Improvement.create(name: "Itens Mágicos IV")
Improvement.create(name: "Magia Duradoura")
Improvement.create(name: "Magia Máxima")
Improvement.create(name: "Magia Sem Gestos")
Improvement.create(name: "Magia Silenciosa")
Improvement.create(name: "Memória Eidética")
Improvement.create(name: "Milícia I")
Improvement.create(name: "Milícia II")
Improvement.create(name: "Milícia III")
Improvement.create(name: "Milícia IV")
Improvement.create(name: "Milícia V")
Improvement.create(name: "Montaria Especial")
Improvement.create(name: "Movimento Rápido")
Improvement.create(name: "Não Precisar Beber ou Comer")
Improvement.create(name: "Noção Exata do Tempo")
Improvement.create(name: "Olhar da Verdade")
Improvement.create(name: "Pacto")
Improvement.create(name: "Patrono")
Improvement.create(name: "Poderes Mágicos")
Improvement.create(name: "Poderes Psiônicos")
Improvement.create(name: "Potencializar Magia")
Improvement.create(name: "Presença Invisível")
Improvement.create(name: "Rastro Invisível")
Improvement.create(name: "Recuperação Mágica Acelerada")
Improvement.create(name: "Recursos e Dinheiro")
Improvement.create(name: "Redução de Dano")
Improvement.create(name: "Reputação")
Improvement.create(name: "Resistência à Dor")
Improvement.create(name: "Resistência à Magia")
Improvement.create(name: "Sábio")
Improvement.create(name: "Saúde de Ferro")
Improvement.create(name: "Sedutor")
Improvement.create(name: "Sensitivo")
Improvement.create(name: "Senso de Direção")
Improvement.create(name: "Senso Numérico")
Improvement.create(name: "Sentidos Aguçados             ")
Improvement.create(name: "Sono Leve")
Improvement.create(name: "Sono Reduzido")
Improvement.create(name: "Sortudo")
Improvement.create(name: "Talento")
Improvement.create(name: "Talento Matemático")
Improvement.create(name: "Temperamento Calmo")
Improvement.create(name: "Tiro Certeiro")
Improvement.create(name: "Tiro em Movimento")
Improvement.create(name: "Tiro Letal")
Improvement.create(name: "Tiro Longo")
Improvement.create(name: "Vida Eterna")
Improvement.create(name: "Visão Noturna ")
Improvement.create(name: "Vontade de Ferro")
Improvement.create(name: "Voz de Comando")

# Aprimoramentos Negativo

Injury.create(name: "Alcoólatra")
Injury.create(name: "Alergia ")
Injury.create(name: "Alergia Grave ")
Injury.create(name: "Alma Vendida")
Injury.create(name: "Alucinado")
Injury.create(name: "Amnésia ")
Injury.create(name: "Andrógeno")
Injury.create(name: "Aparência Trocada")
Injury.create(name: "Arma ou Amuleto Maldito")
Injury.create(name: "Assassino Serial ")
Injury.create(name: "Assombrado")
Injury.create(name: "Azarado")
Injury.create(name: "Canibal")
Injury.create(name: "Casto")
Injury.create(name: "Cético ")
Injury.create(name: "Cleptomaníaco")
Injury.create(name: "Código de Honra")
Injury.create(name: "Complexo de Culpa")
Injury.create(name: "Complexo de Inferioridade")
Injury.create(name: "Compulsão")
Injury.create(name: "Coração Mole")
Injury.create(name: "Covarde")
Injury.create(name: "Crédulo")
Injury.create(name: "Curioso")
Injury.create(name: "Defeito de Ryoga")
Injury.create(name: "Deficiente Físico")
Injury.create(name: "Dependência")
Injury.create(name: "Dificuldade de Fala")
Injury.create(name: "Distração")
Injury.create(name: "Dupla Personalidade")
Injury.create(name: "Esquizofrênico")
Injury.create(name: "Estigma Social")
Injury.create(name: "Família ou Mentor Desonrado")
Injury.create(name: "Fanático")
Injury.create(name: "Fanfarronice")
Injury.create(name: "Ferro Frio")
Injury.create(name: "Fetiche Material")
Injury.create(name: "Fobia")
Injury.create(name: "Fúria")
Injury.create(name: "Galante")
Injury.create(name: "Ganância")
Injury.create(name: "Gremilins")
Injury.create(name: "Gula")
Injury.create(name: "Hábitos Detestáveis")
Injury.create(name: "Hipocondria")
Injury.create(name: "Inimigo")
Injury.create(name: "Intolerância")
Injury.create(name: "Má Fama")
Injury.create(name: "Maldição")
Injury.create(name: "Mania")
Injury.create(name: "Mania de Perseguição")
Injury.create(name: "Maníaco Depressivo")
Injury.create(name: "Marca do Predador")
Injury.create(name: "Mau Humor")
Injury.create(name: "Megalomaníaco ")
Injury.create(name: "Mentiroso Compulsivo")
Injury.create(name: "Monstruoso")
Injury.create(name: "Ódio")
Injury.create(name: "Orgulhoso")
Injury.create(name: "Pacifista")
Injury.create(name: "Perda Terrível")
Injury.create(name: "Perversão Sexual")
Injury.create(name: "Pesadelos")
Injury.create(name: "Poltergeist")
Injury.create(name: "Pupilo")
Injury.create(name: "Restrição à Magia")
Injury.create(name: "Sangramento ")
Injury.create(name: "Sanguinário")
Injury.create(name: "Sarcasmo")
Injury.create(name: "Sono Pesado")
Injury.create(name: "Supersticioso")
Injury.create(name: "Suscetível à Decadência Planar")
Injury.create(name: "Suspeito")
Injury.create(name: "Teimosia")
Injury.create(name: "Timidez")
Injury.create(name: "Toque da Podridão")
Injury.create(name: "Toque Letal")
Injury.create(name: "Traumatizado")
Injury.create(name: "Viciado em Drogas")
Injury.create(name: "Viciado em Jogos")
Injury.create(name: "Visão Monocromática")
Injury.create(name: "Vontade Fraca ")

# Pericias

Skill.create(name: "Armadilha", based_attribute: "INT")
Skill.create(name: "Artes Cênicas", based_attribute: "CAR")
Skill.create(name: "Artes Manuais", based_attribute: "DEX")
Skill.create(name: "Avaliação de Objetos", based_attribute: "PER")
Skill.create(name: "Briga", based_attribute: "DEX")
Skill.create(name: "Caça", based_attribute: "PER")
Skill.create(name: "Camuflagem", based_attribute: "PER")
Skill.create(name: "Concentração", based_attribute: "WILL")
Skill.create(name: "Condução", based_attribute: "AGI")
Skill.create(name: "Explosivos", based_attribute: "-")
Skill.create(name: "Culinária", based_attribute: "PER")
Skill.create(name: "Diplomacia", based_attribute: "CAR")
Skill.create(name: "Disfarce", based_attribute: "INT")
Skill.create(name: "Escapismo", based_attribute: "AGI")
Skill.create(name: "Escudo", based_attribute: "DEX")
Skill.create(name: "Escutar", based_attribute: "PER")
Skill.create(name: "Esquiva", based_attribute: "AGI")
Skill.create(name: "Etiqueta", based_attribute: "CAR")
Skill.create(name: "Falsificação", based_attribute: "INT")
Skill.create(name: "Fuga", based_attribute: "AGI")
Skill.create(name: "Furtar", based_attribute: "DEX")
Skill.create(name: "Furtividade", based_attribute: "AGI")
Skill.create(name: "Herbalismo", based_attribute: "INT")
Skill.create(name: "Idioma", based_attribute: "-")
Skill.create(name: "Leitura Labial", based_attribute: "-")
Skill.create(name: "Manuseio de Fechadura", based_attribute: "DEX")
Skill.create(name: "Navegação", based_attribute: "INT")
Skill.create(name: "Mineração", based_attribute: "-")
Skill.create(name: "Ocultamento", based_attribute: "AGI")
Skill.create(name: "Primeiros Socorros", based_attribute: "INT")
Skill.create(name: "Procurar / Pesquisar", based_attribute: "PER")
Skill.create(name: "Rastreio", based_attribute: "PER")
Skill.create(name: "Sobrevivência", based_attribute: "PER")
Skill.create(name: "Subterfúgio", based_attribute: "PER")
Skill.create(name: "Venefício", based_attribute: "INT")

# Esportes

Skill.create(name: "Acrobacia", based_attribute: "AGI")
Skill.create(name: "Arremesso", based_attribute: "DEX")
Skill.create(name: "Escalada", based_attribute: "FR")
Skill.create(name: "Natação", based_attribute: "AGI")
Skill.create(name: "Salto", based_attribute: "AGI")
Skill.create(name: "Alpinismo", based_attribute: "AGI")
Skill.create(name: "Corrida", based_attribute: "CON")
Skill.create(name: "Mergulho", based_attribute: "CON") 
Skill.create(name: "Pesca", based_attribute: "PER")


# Manobra de Combate
Skill.create(name: "Mira", based_attribute: "30")
Skill.create(name: "Luta às Cegas", based_attribute: "40")
Skill.create(name: "Refém", based_attribute: "30")
Skill.create(name: "Desarme", based_attribute: "40")
Skill.create(name: "Luta com Duas Armas", based_attribute: "50")
Skill.create(name: "Manobras para Impressionar", based_attribute: "30")

# Manipulação
Skill.create(name: "Empatia", based_attribute: "CAR") 
Skill.create(name: "Hipnose", based_attribute: "-") 
Skill.create(name: "Impressionar", based_attribute: "CAR") 
Skill.create(name: "Interrogatório", based_attribute: "INT") 
Skill.create(name: "Intimidação", based_attribute: "WILL") 
Skill.create(name: "Lábia", based_attribute: "CAR") 
Skill.create(name: "Liderança", based_attribute: "CAR") 
Skill.create(name: "Manha", based_attribute: "CAR")
Skill.create(name: "Tortura", based_attribute: "INT")
Skill.create(name: "Sedução", based_attribute: "CAR")

# Ciências Proibidas
Skill.create(name: "Alquimia", based_attribute: "-")
Skill.create(name: "Astrologia", based_attribute: "-")
Skill.create(name: "Teoria da Magia", based_attribute: "-")
Skill.create(name: "Viagem Astral", based_attribute: "-")
Skill.create(name: "Ocultismo", based_attribute: "-")
Skill.create(name: "Rituais", based_attribute: "-")

# Negociação
Skill.create(name: "Barganha", based_attribute: "CAR")
Skill.create(name: "Burocracia", based_attribute: "INT")
Skill.create(name: "Contabilidade", based_attribute: "INT")

# Animais
Skill.create(name: "Tratamento de Animais", based_attribute: "-")
Skill.create(name: "Treinamento de Animais", based_attribute: "-")
Skill.create(name: "Montaria", based_attribute: "AGI")
Skill.create(name: "Doma", based_attribute: "-")
Skill.create(name: "Veterinária", based_attribute: "-")


# Profissoes de Artifice
Skill.create(name: "Carpinteiro (Madeira)", based_attribute: "-")
Skill.create(name: "Costureiro (Tecidos) ", based_attribute: "-")
Skill.create(name: "Coureiro (Couros)", based_attribute: "-")
Skill.create(name: "Ferreiro (Metais)", based_attribute: "-") 
Skill.create(name: "Pedreiro (Pedras) ", based_attribute: "-")
Skill.create(name: "Sapateiro (Couro Rígido)", based_attribute: "-")
Skill.create(name: "Outro", based_attribute: "-")

# Ciências
Skill.create(name: "Agricultura", based_attribute: "INT")
Skill.create(name: "Arqueologia", based_attribute: "INT")
Skill.create(name: "Astronomia", based_attribute: "INT")
Skill.create(name: "Biologia", based_attribute: "INT")
Skill.create(name: "Botânica", based_attribute: "INT")
Skill.create(name: "Geografia", based_attribute: "INT")
Skill.create(name: "História", based_attribute: "INT")
Skill.create(name: "Meteorologia", based_attribute: "INT")
Skill.create(name: "Zoologia", based_attribute: "INT")


# Perícias com Armas
WeaponSkills.create(name: "Faca", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Adaga", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Punhal", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada Curta", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada Longa", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada Bastarda", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada de Duas Mãos", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Mangual", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Mangual Pesado", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Maça", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Maça Estrela", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Martelo de Combate", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Machado de Guerra", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Lança Curta", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Lança Longa", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Arco Curto", based_attribute: "DEX/0")
WeaponSkills.create(name: "Arco Longo", based_attribute: "DEX/0")
WeaponSkills.create(name: "Arco Composto", based_attribute: "DEX/0")
WeaponSkills.create(name: "Funda", based_attribute: "DEX/0")
WeaponSkills.create(name: "Besta Leve", based_attribute: "DEX/0")
WeaponSkills.create(name: "Besta Pesada", based_attribute: "DEX/0")
WeaponSkills.create(name: "Azagaia", based_attribute: "DEX/0")
WeaponSkills.create(name: "Zarabatana", based_attribute: "DEX/0")

# Artilharia
WeaponSkills.create(name: "Aríete", based_attribute: "INT")
WeaponSkills.create(name: "Balestra", based_attribute: "INT")
WeaponSkills.create(name: "Canhão", based_attribute: "INT")
WeaponSkills.create(name: "Catapulta", based_attribute: "INT")