# Aprimoramentos Positivos
Improvement.create(name: "Acerto Crítico Aprimorado I", cost: 1)
Improvement.create(name: "Acerto Crítico Aprimorado II", cost: 2)
Improvement.create(name: "Acerto Crítico Aprimorado III", cost: 3)
Improvement.create(name: "Acuidade com arma", cost: 1)
Improvement.create(name: "Afinidade com Fadas", cost: 3)
Improvement.create(name: "Afinidade com Fadas", cost: 4)
Improvement.create(name: "Afinidade com Fadas", cost: 5)
Improvement.create(name: "Alcance Mágico Extendido", cost: 1)
Improvement.create(name: "Alma Dupla I", cost: 3)
Improvement.create(name: "Alma Dupla II", cost: 4)
Improvement.create(name: "Alma Gêmea", cost: 3)
Improvement.create(name: "Alma Pura", cost: 2)
Improvement.create(name: "Alvo Elusivo I", cost: 1)
Improvement.create(name: "Alvo Elusivo II", cost: 2)
Improvement.create(name: "Ambidestria", cost: 2)
Improvement.create(name: "Ambiente Favorável I", cost: 1)
Improvement.create(name: "Ambiente Favorável II", cost: 2)
Improvement.create(name: "Ambiente Favorável III", cost: 3)
Improvement.create(name: "Ambiente Favorável IV", cost: 4)
Improvement.create(name: "Amor Verdadeiro", cost: 1)
Improvement.create(name: "Aparência Inofensiva", cost: 1)
Improvement.create(name: "Arma ou Amuleto Mágico I", cost: 1)
Improvement.create(name: "Arma ou Amuleto Mágico II", cost: 2)
Improvement.create(name: "Arma Preferencial", cost: 1)
Improvement.create(name: "Armadura de Heróis I", cost: 1)
Improvement.create(name: "Armadura de Heróis II", cost: 2)
Improvement.create(name: "Armadura de Heróis III", cost: 3)
Improvement.create(name: "Ataque Brutal", cost: 1)
Improvement.create(name: "Ataque Desarmado I", cost: 1)
Improvement.create(name: "Ataque Desarmado II", cost: 2)
Improvement.create(name: "Ataque Desarmado III", cost: 3)
Improvement.create(name: "Ataque Desarmado IV", cost: 4)
Improvement.create(name: "Ataque Furtivo I", cost: 1)
Improvement.create(name: "Ataque Furtivo II", cost: 2)
Improvement.create(name: "Ataque Furtivo III", cost: 3)
Improvement.create(name: "Ataque Poderoso", cost: 1)
Improvement.create(name: "Atravessar I", cost: 1)
Improvement.create(name: "Atravessar II", cost: 2)
Improvement.create(name: "Biblioteca I", cost: 1)
Improvement.create(name: "Biblioteca II", cost: 2)
Improvement.create(name: "Biblioteca III", cost: 3)
Improvement.create(name: "Biblioteca IV", cost: 4)
Improvement.create(name: "Biblioteca Mística I", cost: 1)
Improvement.create(name: "Biblioteca Mística II", cost: 2)
Improvement.create(name: "Biblioteca Mística III", cost: 3)
Improvement.create(name: "Bom Senso", cost: 1)
Improvement.create(name: "Caçador de Demônios ou Anjos I", cost: 1)
Improvement.create(name: "Caçador de Demônios ou Anjos II", cost: 2)
Improvement.create(name: "Caminho da Floresta", cost: 1)
Improvement.create(name: "Canalizador I ", cost: 2)
Improvement.create(name: "Canalizador II", cost: 4)
Improvement.create(name: "Capaz de Enxergar Auras", cost: 2)
Improvement.create(name: "Capaz de Enxergar Espíritos", cost: 4)
Improvement.create(name: "Classe Social I", cost: 1)
Improvement.create(name: "Classe Social II", cost: 2)
Improvement.create(name: "Classe Social III", cost: 3)
Improvement.create(name: "Clero I", cost: 1)
Improvement.create(name: "Clero II", cost: 2)
Improvement.create(name: "Clero III", cost: 3)
Improvement.create(name: "Companheiro Animal", cost: 1)
Improvement.create(name: "Comunicação em Sonhos", cost: 2)
Improvement.create(name: "Concentração", cost: 2)
Improvement.create(name: "Conhecimentos Arcanos", cost: 2)
Improvement.create(name: "Conjuração" , cost: 4)
Improvement.create(name: "Contatos e Aliados I", cost: 1)
Improvement.create(name: "Contatos e Aliados II", cost: 2)
Improvement.create(name: "Contatos e Aliados III", cost: 3)
Improvement.create(name: "Contatos e Aliados IV", cost: 4)
Improvement.create(name: "Controle de Multidões", cost: 2)
Improvement.create(name: "Coração de Guerreiro", cost: 2)
Improvement.create(name: "Coragem", cost: 2)
Improvement.create(name: "Corpo Fechado", cost: 2)
Improvement.create(name: "Corpo Maleável", cost: 1)
Improvement.create(name: "Detectar Magia I", cost: 2)
Improvement.create(name: "Detectar Magia II", cost: 3)
Improvement.create(name: "Divida de Gratidão I", cost: 1)
Improvement.create(name: "Divida de Gratidão II", cost: 2)
Improvement.create(name: "Divida de Gratidão III", cost: 3)
Improvement.create(name: "Duro de Matar", cost: 1)
Improvement.create(name: "Efeitos Mágicos Permanentes", cost: 1)
Improvement.create(name: "Eloqüente", cost: 1)
Improvement.create(name: "Empatia com Animais", cost: 1)
Improvement.create(name: "Especialista em Caminho", cost: 1)
Improvement.create(name: "Especialização em Arma I", cost: 1)
Improvement.create(name: "Especialização em Arma II", cost: 2)
Improvement.create(name: "Esquiva Sobrenatural", cost: 1)
Improvement.create(name: "Estender Magia", cost: 1)
Improvement.create(name: "Evasão", cost: 1)
Improvement.create(name: "Fama I", cost: 1)
Improvement.create(name: "Fama II", cost: 2)
Improvement.create(name: "Fama III", cost: 3)
Improvement.create(name: "Fama IV", cost: 4)
Improvement.create(name: "Família ou Mentor Honrado", cost: 1)
Improvement.create(name: "Familiares", cost: 2)
Improvement.create(name: "Gremilins", cost: 3)
Improvement.create(name: "Guardião I", cost: 2)
Improvement.create(name: "Guardião II", cost: 3)
Improvement.create(name: "Guardião de Artefato", cost: 3)
Improvement.create(name: "Homúnculo", cost: 2)
Improvement.create(name: "Identidade Secreta", cost: 1)
Improvement.create(name: "Improvisador I", cost: 1)
Improvement.create(name: "Improvisador II", cost: 2)
Improvement.create(name: "Imunidade a Venenos I", cost: 2)
Improvement.create(name: "Imunidade a Venenos II", cost: 3)
Improvement.create(name: "Infravisão", cost: 2)
Improvement.create(name: "Inimigo Favorito", cost: 1)
Improvement.create(name: "Inocência I", cost: 1)
Improvement.create(name: "Inocência II", cost: 2)
Improvement.create(name: "Itens Mágicos I", cost: 1)
Improvement.create(name: "Itens Mágicos II", cost: 2)
Improvement.create(name: "Itens Mágicos III", cost: 3)
Improvement.create(name: "Itens Mágicos IV", cost: 4)
Improvement.create(name: "Magia Duradoura", cost: 1)
Improvement.create(name: "Magia Máxima", cost: 4)
Improvement.create(name: "Magia Sem Gestos", cost: 1)
Improvement.create(name: "Magia Silenciosa", cost: 1)
Improvement.create(name: "Memória Eidética", cost: 1)
Improvement.create(name: "Milícia I", cost: 1)
Improvement.create(name: "Milícia II", cost: 2)
Improvement.create(name: "Milícia III", cost: 3)
Improvement.create(name: "Milícia IV", cost: 4)
Improvement.create(name: "Milícia V", cost: 5)
Improvement.create(name: "Montaria Especial", cost: 2)
Improvement.create(name: "Movimento Rápido", cost: 1)
Improvement.create(name: "Não Precisar Beber ou Comer I", cost: 2)
Improvement.create(name: "Não Precisar Beber ou Comer II", cost: 3)
Improvement.create(name: "Noção Exata do Tempo", cost: 1)
Improvement.create(name: "Olhar da Verdade", cost: 2)
Improvement.create(name: "Pacto", cost: 1)
Improvement.create(name: "Patrono", cost: 2)
Improvement.create(name: "Poderes Mágicos I", cost: 1)
Improvement.create(name: "Poderes Mágicos II", cost: 2)
Improvement.create(name: "Poderes Mágicos III", cost: 3)
Improvement.create(name: "Poderes Mágicos IV", cost: 4)
Improvement.create(name: "Poderes Mágicos V", cost: 5)
Improvement.create(name: "Poderes Psiônicos I", cost: 1)
Improvement.create(name: "Poderes Psiônicos II", cost: 2)
Improvement.create(name: "Poderes Psiônicos III", cost: 3)
Improvement.create(name: "Poderes Psiônicos IV", cost: 4)
Improvement.create(name: "Poderes Psiônicos V", cost: 5)
Improvement.create(name: "Pontos de Fé I", cost: 1)
Improvement.create(name: "Pontos de Fé II", cost: 2)
Improvement.create(name: "Pontos de Fé III", cost: 3)
Improvement.create(name: "Pontos de Fé IV", cost: 4)
Improvement.create(name: "Pontos de Fé V", cost: 5)
Improvement.create(name: "Pontos de Mágia Extra", cost: 2)
Improvement.create(name: "Pontos Heróicos I", cost: 1)
Improvement.create(name: "Pontos Heróicos II", cost: 2)
Improvement.create(name: "Pontos Heróicos III", cost: 3)
Improvement.create(name: "Pontos Heróicos IV", cost: 4)
Improvement.create(name: "Potencializar Magia", cost: 1)
Improvement.create(name: "Presença Invisível", cost: 2)
Improvement.create(name: "Rastro Invisível", cost: 1)
Improvement.create(name: "Recuperação Mágica Acelerada", cost: 2)
Improvement.create(name: "Recursos e Dinheiro I", cost: 1)
Improvement.create(name: "Recursos e Dinheiro II", cost: 2)
Improvement.create(name: "Recursos e Dinheiro III", cost: 3)
Improvement.create(name: "Recursos e Dinheiro IV", cost: 4)
Improvement.create(name: "Recursos e Dinheiro V", cost: 5)
Improvement.create(name: "Redução de Dano I", cost: 1)
Improvement.create(name: "Redução de Dano II", cost: 2)
Improvement.create(name: "Redução de Dano III", cost: 3)
Improvement.create(name: "Reputação I", cost: 2)
Improvement.create(name: "Reputação II", cost: 3)
Improvement.create(name: "Reputação III", cost: 4)
Improvement.create(name: "Resistência à Dor", cost: 3)
Improvement.create(name: "Resistência à Magia I", cost: 1)
Improvement.create(name: "Resistência à Magia II", cost: 2)
Improvement.create(name: "Resistência à Magia III", cost: 3)
Improvement.create(name: "Resistência à Magia IV", cost: 4)
Improvement.create(name: "Resistência à Magia V", cost: 5)
Improvement.create(name: "Sábio", cost: 1)
Improvement.create(name: "Saúde de Ferro", cost: 1)
Improvement.create(name: "Sedutor", cost: 1)
Improvement.create(name: "Sensitivo I", cost: 1)
Improvement.create(name: "Sensitivo II", cost: 2)
Improvement.create(name: "Senso de Direção I", cost: 1)
Improvement.create(name: "Senso de Direção II", cost: 2)
Improvement.create(name: "Senso Numérico", cost: 1)
Improvement.create(name: "Sentidos Aguçados", cost: 1)
Improvement.create(name: "Sono Leve I", cost: 1)
Improvement.create(name: "Sono Leve II", cost: 2)
Improvement.create(name: "Sono Reduzido", cost: 1)
Improvement.create(name: "Sortudo I", cost: 2)
Improvement.create(name: "Sortudo II", cost: 3)
Improvement.create(name: "Talento", cost: 1)
Improvement.create(name: "Talento Matemático", cost: 1)
Improvement.create(name: "Temperamento Calmo", cost: 2)
Improvement.create(name: "Tiro Certeiro", cost: 1)
Improvement.create(name: "Tiro em Movimento", cost: 1)
Improvement.create(name: "Tiro Letal", cost: 1)
Improvement.create(name: "Tiro Longo", cost: 1)
Improvement.create(name: "Vida Eterna I", cost: 3)
Improvement.create(name: "Vida Eterna II", cost: 4)
Improvement.create(name: "Vida Eterna III", cost: 5)
Improvement.create(name: "Visão Noturna", cost: 2)
Improvement.create(name: "Vontade de Ferro", cost: 2)
Improvement.create(name: "Voz de Comando", cost: 4)

# Aprimoramentos Negativo

Injury.create(name: "Alcoólatra", cost: 1)
Injury.create(name: "Alergia", cost: 1)
Injury.create(name: "Alergia Grave", cost: 2)
Injury.create(name: "Alma Vendida", cost: 2)
Injury.create(name: "Alucinado", cost: 2)
Injury.create(name: "Amnésia", cost: 1)
Injury.create(name: "Andrógeno", cost: 1)
Injury.create(name: "Aparência Trocada", cost: 1)
Injury.create(name: "Arma ou Amuleto Maldito I", cost: 1)
Injury.create(name: "Arma ou Amuleto Maldito II", cost: 2)
Injury.create(name: "Assassino Serial I", cost: 2)
Injury.create(name: "Assassino Serial II", cost: 3)
Injury.create(name: "Assombrado", cost: 1)
Injury.create(name: "Azarado", cost: 1)
Injury.create(name: "Canibal", cost: 3)
Injury.create(name: "Casto", cost: 1)
Injury.create(name: "Cético", cost: 1)
Injury.create(name: "Cleptomaníaco", cost: 2)
Injury.create(name: "Código de Honra", cost: 1)
Injury.create(name: "Complexo de Culpa", cost: 1)
Injury.create(name: "Complexo de Inferioridade", cost: 1)
Injury.create(name: "Compulsão", cost: 1)
Injury.create(name: "Coração Mole", cost: 1)
Injury.create(name: "Covarde", cost: 1)
Injury.create(name: "Crédulo", cost: 1)
Injury.create(name: "Curioso", cost: 1)
Injury.create(name: "Defeito de Ryoga", cost: 1)
Injury.create(name: "Deficiente Físico I", cost: 1)
Injury.create(name: "Deficiente Físico II", cost: 2)
Injury.create(name: "Deficiente Físico III", cost: 3)
Injury.create(name: "Dependência", cost: 2)
Injury.create(name: "Dificuldade de Fala", cost: 1)
Injury.create(name: "Distração", cost: 1)
Injury.create(name: "Dupla Personalidade", cost: 3)
Injury.create(name: "Esquizofrênico", cost: 2)
Injury.create(name: "Estigma Social", cost: 1)
Injury.create(name: "Família ou Mentor Desonrado", cost: 1)
Injury.create(name: "Fanático", cost: 2)
Injury.create(name: "Fanfarronice", cost: 1)
Injury.create(name: "Ferro Frio", cost: 2)
Injury.create(name: "Fetiche Material I", cost: 1)
Injury.create(name: "Fetiche Material II", cost: 2)
Injury.create(name: "Fobia I", cost: 1)
Injury.create(name: "Fobia II", cost: 2)
Injury.create(name: "Fúria", cost: 2)
Injury.create(name: "Galante", cost: 1)
Injury.create(name: "Ganância", cost: 1)
Injury.create(name: "Gremilins", cost: 3)
Injury.create(name: "Gula", cost: 1)
Injury.create(name: "Hábitos Detestáveis", cost: 1)
Injury.create(name: "Hipocondria", cost: 1)
Injury.create(name: "Inimigo", cost: 1)
Injury.create(name: "Intolerância", cost: 1)
Injury.create(name: "Má Fama I", cost: 1)
Injury.create(name: "Má Fama II", cost: 3)
Injury.create(name: "Maldição I", cost: 1)
Injury.create(name: "Maldição II", cost: 2)
Injury.create(name: "Maldição III", cost: 3)
Injury.create(name: "Mania", cost: 1)
Injury.create(name: "Mania de Perseguição", cost: 1)
Injury.create(name: "Maníaco Depressivo", cost: 2)
Injury.create(name: "Marca do Predador", cost: 1)
Injury.create(name: "Mau Humor", cost: 1)
Injury.create(name: "Megalomaníaco", cost: 1)
Injury.create(name: "Mentiroso Compulsivo", cost: 2)
Injury.create(name: "Monstruoso", cost: 1)
Injury.create(name: "Ódio", cost: 1)
Injury.create(name: "Orgulhoso", cost: 1)
Injury.create(name: "Pacifista I", cost: 1)
Injury.create(name: "Pacifista II", cost: 2)
Injury.create(name: "Pacifista III", cost: 3)
Injury.create(name: "Perda Terrível", cost: 1)
Injury.create(name: "Perversão Sexual I", cost: 1)
Injury.create(name: "Perversão Sexual II", cost: 2)
Injury.create(name: "Perversão Sexual III", cost: 3)
Injury.create(name: "Pesadelos", cost: 1)
Injury.create(name: "Poltergeist", cost: 2)
Injury.create(name: "Pupilo", cost: 1)
Injury.create(name: "Restrição à Magia I", cost: 2)
Injury.create(name: "Restrição à Magia II", cost: 3)
Injury.create(name: "Sangramento", cost: 2)
Injury.create(name: "Sanguinário", cost: 1)
Injury.create(name: "Sarcasmo", cost: 1)
Injury.create(name: "Sono Pesado", cost: 1)
Injury.create(name: "Supersticioso", cost: 1)
Injury.create(name: "Suscetível à Decadência Planar I", cost: 1)
Injury.create(name: "Suscetível à Decadência Planar II", cost: 2)
Injury.create(name: "Suscetível à Decadência Planar III", cost: 3)
Injury.create(name: "Suspeito I", cost: 1)
Injury.create(name: "Suspeito II", cost: 2)
Injury.create(name: "Teimosia", cost: 1)
Injury.create(name: "Timidez", cost: 1)
Injury.create(name: "Toque da Podridão", cost: 3)
Injury.create(name: "Toque Letal", cost: 2)
Injury.create(name: "Traumatizado", cost: 2)
Injury.create(name: "Viciado em Drogas", cost: 1)
Injury.create(name: "Viciado em Jogos", cost: 1)
Injury.create(name: "Visão Monocromática", cost: 1)
Injury.create(name: "Vontade Fraca", cost: 1)

# Pericias

Skill.create(name: "Armadilha", based_attribute: "INT")
Skill.create(name: "Artes Cênicas", based_attribute: "CAR")
Skill.create(name: "Artes Manuais", based_attribute: "DEX")
Skill.create(name: "Avaliação de Objetos", based_attribute: "PER")
Skill.create(name: "Briga", based_attribute: "DEX")
Skill.create(name: "Caça", based_attribute: "PER")
Skill.create(name: "Camuflagem", based_attribute: "PER")
Skill.create(name: "Concentração", based_attribute: "WILL")
Skill.create(name: "Condução", based_attribute: "AGI")
Skill.create(name: "Explosivos", based_attribute: "-")
Skill.create(name: "Culinária", based_attribute: "PER")
Skill.create(name: "Diplomacia", based_attribute: "CAR")
Skill.create(name: "Disfarce", based_attribute: "INT")
Skill.create(name: "Escapismo", based_attribute: "AGI")
Skill.create(name: "Escudo", based_attribute: "DEX")
Skill.create(name: "Escutar", based_attribute: "PER")
Skill.create(name: "Esquiva", based_attribute: "AGI")
Skill.create(name: "Etiqueta", based_attribute: "CAR")
Skill.create(name: "Falsificação", based_attribute: "INT")
Skill.create(name: "Fuga", based_attribute: "AGI")
Skill.create(name: "Furtar", based_attribute: "DEX")
Skill.create(name: "Furtividade", based_attribute: "AGI")
Skill.create(name: "Herbalismo", based_attribute: "INT")
Skill.create(name: "Idioma", based_attribute: "-")
Skill.create(name: "Leitura Labial", based_attribute: "-")
Skill.create(name: "Manuseio de Fechadura", based_attribute: "DEX")
Skill.create(name: "Navegação", based_attribute: "INT")
Skill.create(name: "Mineração", based_attribute: "-")
Skill.create(name: "Ocultamento", based_attribute: "AGI")
Skill.create(name: "Primeiros Socorros", based_attribute: "INT")
Skill.create(name: "Procurar / Pesquisar", based_attribute: "PER")
Skill.create(name: "Rastreio", based_attribute: "PER")
Skill.create(name: "Sobrevivência", based_attribute: "PER")
Skill.create(name: "Subterfúgio", based_attribute: "PER")
Skill.create(name: "Venefício", based_attribute: "INT")

# Esportes

Skill.create(name: "Acrobacia", based_attribute: "AGI")
Skill.create(name: "Arremesso", based_attribute: "DEX")
Skill.create(name: "Escalada", based_attribute: "FR")
Skill.create(name: "Natação", based_attribute: "AGI")
Skill.create(name: "Salto", based_attribute: "AGI")
Skill.create(name: "Alpinismo", based_attribute: "AGI")
Skill.create(name: "Corrida", based_attribute: "CON")
Skill.create(name: "Mergulho", based_attribute: "CON") 
Skill.create(name: "Pesca", based_attribute: "PER")


# Manobra de Combate
Skill.create(name: "Mira", based_attribute: "30")
Skill.create(name: "Luta às Cegas", based_attribute: "40")
Skill.create(name: "Refém", based_attribute: "30")
Skill.create(name: "Desarme", based_attribute: "40")
Skill.create(name: "Luta com Duas Armas", based_attribute: "50")
Skill.create(name: "Manobras para Impressionar", based_attribute: "30")

# Manipulação
Skill.create(name: "Empatia", based_attribute: "CAR") 
Skill.create(name: "Hipnose", based_attribute: "-") 
Skill.create(name: "Impressionar", based_attribute: "CAR") 
Skill.create(name: "Interrogatório", based_attribute: "INT") 
Skill.create(name: "Intimidação", based_attribute: "WILL") 
Skill.create(name: "Lábia", based_attribute: "CAR") 
Skill.create(name: "Liderança", based_attribute: "CAR") 
Skill.create(name: "Manha", based_attribute: "CAR")
Skill.create(name: "Tortura", based_attribute: "INT")
Skill.create(name: "Sedução", based_attribute: "CAR")

# Ciências Proibidas
Skill.create(name: "Alquimia", based_attribute: "-")
Skill.create(name: "Astrologia", based_attribute: "-")
Skill.create(name: "Teoria da Magia", based_attribute: "-")
Skill.create(name: "Viagem Astral", based_attribute: "-")
Skill.create(name: "Ocultismo", based_attribute: "-")
Skill.create(name: "Rituais", based_attribute: "-")

# Negociação
Skill.create(name: "Barganha", based_attribute: "CAR")
Skill.create(name: "Burocracia", based_attribute: "INT")
Skill.create(name: "Contabilidade", based_attribute: "INT")

# Animais
Skill.create(name: "Tratamento de Animais", based_attribute: "-")
Skill.create(name: "Treinamento de Animais", based_attribute: "-")
Skill.create(name: "Montaria", based_attribute: "AGI")
Skill.create(name: "Doma", based_attribute: "-")
Skill.create(name: "Veterinária", based_attribute: "-")


# Profissoes de Artifice
Skill.create(name: "Carpinteiro (Madeira)", based_attribute: "-")
Skill.create(name: "Costureiro (Tecidos) ", based_attribute: "-")
Skill.create(name: "Coureiro (Couros)", based_attribute: "-")
Skill.create(name: "Ferreiro (Metais)", based_attribute: "-") 
Skill.create(name: "Pedreiro (Pedras) ", based_attribute: "-")
Skill.create(name: "Sapateiro (Couro Rígido)", based_attribute: "-")
Skill.create(name: "Outro", based_attribute: "-")

# Ciências
Skill.create(name: "Agricultura", based_attribute: "INT")
Skill.create(name: "Arqueologia", based_attribute: "INT")
Skill.create(name: "Astronomia", based_attribute: "INT")
Skill.create(name: "Biologia", based_attribute: "INT")
Skill.create(name: "Botânica", based_attribute: "INT")
Skill.create(name: "Geografia", based_attribute: "INT")
Skill.create(name: "História", based_attribute: "INT")
Skill.create(name: "Meteorologia", based_attribute: "INT")
Skill.create(name: "Zoologia", based_attribute: "INT")


# Perícias com Armas
WeaponSkills.create(name: "Faca", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Adaga", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Punhal", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada Curta", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada Longa", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada Bastarda", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Espada de Duas Mãos", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Mangual", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Mangual Pesado", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Maça", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Maça Estrela", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Martelo de Combate", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Machado de Guerra", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Lança Curta", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Lança Longa", based_attribute: "DEX/DEX")
WeaponSkills.create(name: "Arco Curto", based_attribute: "DEX/0")
WeaponSkills.create(name: "Arco Longo", based_attribute: "DEX/0")
WeaponSkills.create(name: "Arco Composto", based_attribute: "DEX/0")
WeaponSkills.create(name: "Funda", based_attribute: "DEX/0")
WeaponSkills.create(name: "Besta Leve", based_attribute: "DEX/0")
WeaponSkills.create(name: "Besta Pesada", based_attribute: "DEX/0")
WeaponSkills.create(name: "Azagaia", based_attribute: "DEX/0")
WeaponSkills.create(name: "Zarabatana", based_attribute: "DEX/0")

# Artilharia
WeaponSkills.create(name: "Aríete", based_attribute: "INT")
WeaponSkills.create(name: "Balestra", based_attribute: "INT")
WeaponSkills.create(name: "Canhão", based_attribute: "INT")
WeaponSkills.create(name: "Catapulta", based_attribute: "INT")